name: Node.js CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ''

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/apps/portfolio-website/
          pwd
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          git fetch --all
          git reset --hard origin/master
          npm i
          git status
          npm run build
          # Move dist directory to /var/www/portfolio-website
          mkdir -p /var/www/portfolio-website
          rm -r /var/www/portfolio-website/dist/*
          mv dist /var/www/portfolio-website

